from flask import Flask, request, jsonify, Response
from flask_cors import CORS
from datetime import datetime, date
import psycopg2
import psycopg2.extras
import os
import glob

app = Flask(__name__)

CORS(app, resources={r"/api/*": {"origins": ["http://localhost:1234", "http://localhost:5678"]}})

# ============================================================
# DB CONFIG
# ============================================================
DB_CONFIG = {
    "host": "localhost",
    "port": 1234,
    "database": "alertas_soc",
    "user": "postgres_user",
    "password": "DB_PASSWORD",
}

LOG_DIR = "logs"

# ============================================================
# EXPORT CONFIG
# ============================================================
# Path to the self-contained HTML file generated by auto_export.py.
# This is the file served by GET /export and uploaded to SharePoint by the SOAR.
# Must match OUTPUT_HTML_PATH in auto_export.py.
EXPORT_HTML_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "exports", "soc_dashboard.html")

# Kept for backward compatibility / debugging (JSON snapshot).
# Must match OUTPUT_PATH in auto_export.py.
EXPORT_JSON_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "exports", "predicted_events.json")

# ============================================================
# DB HELPERS
# ============================================================
def get_conn():
    return psycopg2.connect(**DB_CONFIG)

def query(conn_fn, sql, params=None):
    """Run a SELECT and return list of dicts."""
    conn = conn_fn()
    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, params or ())
            return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()

def query_one(conn_fn, sql, params=None):
    """Run a SELECT and return a single dict (or None)."""
    rows = query(conn_fn, sql, params)
    return rows[0] if rows else None

def serialize(obj):
    """Make datetime/date JSON-serialisable."""
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    return obj

def serialize_rows(rows):
    return [{k: serialize(v) for k, v in row.items()} for row in rows]


# ============================================================
# ============================================================
# CORE ENDPOINTS — SOAR ingest + export (NO dashboard)
#   /test    GET   — health check
#   /event   POST  — ingesta del SOAR (event_id -> ids.eventos)
#   /export  GET   — entrega del JSON de predicciones al SOAR
# ============================================================
# ============================================================

@app.route("/test", methods=["GET"])
def test():
    return "Flask funcionando", 200


@app.route("/event", methods=["POST"])
def receive_event():
    data = request.get_json(silent=True)

    if not data:
        return jsonify({"error": "Body JSON requerido"}), 400

    if "event_id" not in data:
        return jsonify({"error": "event_id requerido"}), 400

    event_id = str(data["event_id"]).strip()
    event_time = data.get("event_time")

    if not event_id:
        return jsonify({"error": "event_id vacío"}), 400

    try:
        save_event_id(event_id, event_time)
        return jsonify({"status": "ok", "event_id": event_id, "event_time": event_time}), 200
    except Exception as e:
        return jsonify({"status": "error", "error": str(e)}), 500


def save_event_id(event_id: str, event_time: str | None):
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO ids.eventos (source_event_id, event_time)
                VALUES (%s, %s)
                ON CONFLICT (source_event_id) DO UPDATE
                SET event_time = EXCLUDED.event_time;
                """,
                (event_id, event_time)
            )
        conn.commit()
    finally:
        conn.close()


@app.route("/export", methods=["GET"])
def export_predicted():
    """
    Entrega al SOAR / Automation Factory l'HTML autònom de prediccions.

    Retorna el fitxer soc_dashboard.html generat per auto_export.py, que ja
    porta les dades de predicted.eventos integrades com a constant JS. El SOAR
    penja directament aquest HTML a SharePoint; no necessita el JSON a part.

    El fitxer es genera atòmicament (temp + rename), de manera que un lector
    mai veurà un fitxer a mig escriure.

    Codis d'estat:
      200  - fitxer trobat i retornat (text/html)
      404  - el fitxer encara no existeix (auto_export.py no ha corregut)
      500  - el fitxer existeix però no s'ha pogut llegir
    """
    try:
        if not os.path.exists(EXPORT_HTML_PATH):
            return jsonify({"error": "export not available yet — run auto_export.py first"}), 404

        with open(EXPORT_HTML_PATH, "r", encoding="utf-8") as f:
            content = f.read()

        return Response(content, status=200, mimetype="text/html; charset=utf-8")

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# ============================================================
# WEB INTERFACE (DASHBOARD) API — endpoints /api/*
#   Los consume el frontend React. NO los toca el SOAR.
# ============================================================
# ============================================================

# ============================================================
# API: STATS — Global KPIs for the dashboard home
# ============================================================

@app.route("/api/stats", methods=["GET"])
def api_stats():
    """
    Returns global counters used by the dashboard home page.

    Response shape:
    {
        "total_received":   int,   -- all event_ids ever received from SOAR
        "queue_pending":    int,   -- waiting in alertas_ids (not yet in Splunk)
        "queue_failed":     int,   -- failed after MAX_ATTEMPTS in alertas_ids
        "encoded_pending":  int,   -- waiting in alertas_encoded (not yet classified)
        "encoded_failed":   int,   -- failed in alertas_encoded
        "total_predicted":  int,   -- total events classified
        "total_tp":         int,   -- True Positives
        "total_fp":         int,   -- False Positives
        "tp_pct":           float, -- % of TP over total predicted
        "fp_pct":           float, -- % of FP over total predicted
        "predicted_today":  int,   -- events classified today
        "tp_today":         int,   -- TP classified today
        "fp_today":         int,   -- FP classified today
        "proc_count":       int,   -- alerts with a measured processing time
        "proc_avg":         float, -- average processing time (seconds)
        "proc_p50":         float, -- median processing time (seconds)
        "proc_p95":         float, -- 95th percentile processing time (seconds)
        "proc_min":         float, -- fastest processed alert (seconds)
        "proc_max":         float, -- slowest processed alert (seconds)
        "proc_count_today": int,   -- alerts measured today
        "proc_avg_today":   float  -- average processing time today (seconds)
    }
    Processing time = classification timestamp - moment auto_splunk picked the
    alert from ids.eventos. Queue wait time is intentionally NOT included.
    """
    try:
        # --- ids stats ---
        ids_data = query_one(
            get_conn,
            "SELECT COUNT(*) AS total FROM ids.eventos"
        )
        queue_pending = query_one(
            get_conn,
            "SELECT COUNT(*) AS cnt FROM ids.eventos WHERE attempt_count = 0 OR attempt_count IS NULL"
        )
        queue_failed = query_one(
            get_conn,
            "SELECT COUNT(*) AS cnt FROM ids.eventos_fallidos"
        )

        # --- encoded stats ---
        encoded_pending = query_one(
            get_conn,
            "SELECT COUNT(*) AS cnt FROM encoded.eventos"
        )
        encoded_failed = query_one(
            get_conn,
            "SELECT COUNT(*) AS cnt FROM encoded.eventos_fallidos"
        )

        # --- predicted stats ---
        pred_total = query_one(
            get_conn,
            "SELECT COUNT(*) AS total, "
            "  SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp, "
            "  SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp "
            "FROM predicted.eventos"
        )
        pred_today = query_one(
            get_conn,
            "SELECT COUNT(*) AS total, "
            "  SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp, "
            "  SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp "
            "FROM predicted.eventos "
            "WHERE created_at::date = CURRENT_DATE"
        )

        # --- processing-time stats (temps de processament per alerta) ---
        # processing_seconds = classificació - inici de processament a auto_splunk.
        # Només es comptabilitzen les alertes amb el cronòmetre mesurat (NOT NULL).
        proc = query_one(
            get_conn,
            """
            SELECT
                COUNT(processing_seconds)                                          AS cnt,
                AVG(processing_seconds)                                            AS avg_s,
                PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY processing_seconds)   AS p50,
                PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY processing_seconds)   AS p95,
                MIN(processing_seconds)                                            AS min_s,
                MAX(processing_seconds)                                            AS max_s
            FROM predicted.eventos
            WHERE processing_seconds IS NOT NULL
            """
        )
        proc_today = query_one(
            get_conn,
            """
            SELECT
                COUNT(processing_seconds) AS cnt,
                AVG(processing_seconds)   AS avg_s
            FROM predicted.eventos
            WHERE processing_seconds IS NOT NULL
              AND created_at::date = CURRENT_DATE
            """
        )

        total     = int(pred_total["total"] or 0)
        tp        = int(pred_total["tp"]    or 0)
        fp        = int(pred_total["fp"]    or 0)

        def r2(v):
            """Round to 2 decimals, keeping None as None."""
            return round(float(v), 2) if v is not None else None

        return jsonify({
            "total_received":  int(ids_data["total"]       or 0),
            "queue_pending":   int(queue_pending["cnt"]    or 0),
            "queue_failed":    int(queue_failed["cnt"]     or 0),
            "encoded_pending": int(encoded_pending["cnt"]  or 0),
            "encoded_failed":  int(encoded_failed["cnt"]   or 0),
            "total_predicted": total,
            "total_tp":        tp,
            "total_fp":        fp,
            "tp_pct":          round(tp / total * 100, 1) if total else 0,
            "fp_pct":          round(fp / total * 100, 1) if total else 0,
            "predicted_today": int(pred_today["total"] or 0),
            "tp_today":        int(pred_today["tp"]    or 0),
            "fp_today":        int(pred_today["fp"]    or 0),

            # --- processing time (segons per alerta, des de l'inici a auto_splunk
            #     fins a la classificació; exclou el temps de cua) ---
            "proc_count":       int(proc["cnt"]   or 0),
            "proc_avg":         r2(proc["avg_s"]),
            "proc_p50":         r2(proc["p50"]),
            "proc_p95":         r2(proc["p95"]),
            "proc_min":         r2(proc["min_s"]),
            "proc_max":         r2(proc["max_s"]),
            "proc_count_today": int(proc_today["cnt"] or 0),
            "proc_avg_today":   r2(proc_today["avg_s"]),
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: QUEUE — alertas_ids content
# ============================================================

@app.route("/api/queue", methods=["GET"])
def api_queue():
    """
    Returns the current content of alertas_ids.

    Query params:
      ?table=pending|failed   (default: pending)
      ?limit=N                (default: 100)

    Response shape:
    {
        "table":  "pending" | "failed",
        "count":  int,
        "rows": [
            {
                "id":              int,
                "source_event_id": str,
                "event_time":      str | null,
                "received_at":     str,
                "attempt_count":   int,
                "last_attempt_at": str | null
            },
            ...
        ]
    }
    """
    try:
        table  = request.args.get("table", "pending")
        limit  = min(int(request.args.get("limit", 100)), 500)

        if table == "failed":
            sql = "SELECT * FROM ids.eventos_fallidos ORDER BY received_at DESC LIMIT %s"
        else:
            sql = "SELECT * FROM ids.eventos ORDER BY received_at DESC LIMIT %s"

        rows = query(get_conn, sql, (limit,))
        return jsonify({"table": table, "count": len(rows), "rows": serialize_rows(rows)})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: ENCODED — alertas_encoded content
# ============================================================

@app.route("/api/encoded", methods=["GET"])
def api_encoded():
    """
    Returns the current content of alertas_encoded.

    Query params:
      ?table=pending|failed   (default: pending)
      ?limit=N                (default: 100)

    Response shape:
    {
        "table":  "pending" | "failed",
        "count":  int,
        "rows": [
            {
                "source_event_id": str,
                "orig_client":     str | null,
                "orig_rule_title": str | null,
                "severity":        str | null,
                "src_ip":          str | null,
                "dest_ip":         str | null,
                "action":          str | null,
                "attempt_count":   int,
                "last_attempt_at": str | null,
                "created_at":      str,
                -- (only in failed table):
                "last_error":      str | null
            },
            ...
        ]
    }
    """
    try:
        table = request.args.get("table", "pending")
        limit = min(int(request.args.get("limit", 100)), 500)

        if table == "failed":
            sql = """
                SELECT source_event_id, orig_client, orig_index, orig_rule_title,
                       severity, src_ip, dest_ip, dest_port, action, signature,
                       country, attempt_count, last_attempt_at, last_error
                FROM encoded.eventos_fallidos
                ORDER BY last_attempt_at DESC
                LIMIT %s
            """
        else:
            sql = """
                SELECT source_event_id, orig_client, orig_index, orig_rule_title,
                       severity, src_ip, dest_ip, dest_port, action, signature,
                       country, attempt_count, last_attempt_at, created_at
                FROM encoded.eventos
                ORDER BY created_at DESC
                LIMIT %s
            """

        rows = query(get_conn, sql, (limit,))
        return jsonify({"table": table, "count": len(rows), "rows": serialize_rows(rows)})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: PREDICTED — alertas_predicted content + filters
# ============================================================

@app.route("/api/predicted", methods=["GET"])
def api_predicted():
    """
    Returns classified events from alertas_predicted.

    Query params:
      ?verdict=all|tp|fp      (default: all)
      ?limit=N                (default: 100)
      ?offset=N               (default: 0,  for pagination)
      ?date_from=YYYY-MM-DD   (optional)
      ?date_to=YYYY-MM-DD     (optional)
      ?client=CLIENT_NAME     (optional, filter by orig_client)

    Response shape:
    {
        "total":  int,   -- total rows matching filter (before limit/offset)
        "count":  int,   -- rows returned in this page
        "rows": [
            {
                "source_event_id": str,
                "orig_client":     str | null,
                "orig_rule_title": str | null,
                "severity":        str | null,
                "src_ip":          str | null,
                "dest_ip":         str | null,
                "action":          str | null,
                "signature":       str | null,
                "country":         str | null,
                "prediction":      bool,
                "score":           float | null,
                "processing_seconds": float | null,  -- pipeline time for this alert
                "created_at":      str
            },
            ...
        ]
    }
    """
    try:
        verdict    = request.args.get("verdict", "all")
        limit      = min(int(request.args.get("limit",  100)), 500)
        offset     = int(request.args.get("offset", 0))
        date_from  = request.args.get("date_from")
        date_to    = request.args.get("date_to")
        client     = request.args.get("client")

        conditions = []
        params     = []

        if verdict == "tp":
            conditions.append("prediction = true")
        elif verdict == "fp":
            conditions.append("prediction = false")

        if date_from:
            conditions.append("created_at::date >= %s")
            params.append(date_from)

        if date_to:
            conditions.append("created_at::date <= %s")
            params.append(date_to)

        if client:
            conditions.append("orig_client = %s")
            params.append(client)

        where = ("WHERE " + " AND ".join(conditions)) if conditions else ""

        # Total count (for pagination)
        count_row = query_one(
            get_conn,
            f"SELECT COUNT(*) AS total FROM predicted.eventos {where}",
            params
        )
        total = int(count_row["total"] or 0)

        # Actual rows
        rows = query(
            get_conn,
            f"""
            SELECT source_event_id, orig_client, orig_rule_title, rule_description,
                   severity, src_ip, dest_ip, dest_port, action, signature, country,
                   "user", hostname, sender, subject, recipient, url,
                   prediction, score, created_at, processing_seconds
            FROM predicted.eventos
            {where}
            ORDER BY created_at DESC
            LIMIT %s OFFSET %s
            """,
            params + [limit, offset]
        )

        return jsonify({"total": total, "count": len(rows), "rows": serialize_rows(rows)})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: CHART DATA — aggregated data for graphs
# ============================================================

@app.route("/api/charts/daily", methods=["GET"])
def api_charts_daily():
    """
    Returns TP/FP counts grouped by day (last N days).

    Query params:
      ?days=N   (default: 30)

    Response shape:
    {
        "rows": [
            { "day": "2025-05-01", "tp": 12, "fp": 5, "total": 17 },
            ...
        ]
    }
    """
    try:
        days = min(int(request.args.get("days", 30)), 365)

        rows = query(
            get_conn,
            """
            SELECT
                created_at::date AS day,
                SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp,
                SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp,
                COUNT(*) AS total
            FROM predicted.eventos
            WHERE created_at >= CURRENT_DATE - (%s * INTERVAL '1 day')
            GROUP BY created_at::date
            ORDER BY day ASC
            """,
            (days,)
        )

        return jsonify({"rows": serialize_rows(rows)})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/charts/score_distribution", methods=["GET"])
def api_charts_score_distribution():
    """
    Returns score distribution in buckets of 0.05 width.
    Useful to render a histogram of model confidence.

    Response shape:
    {
        "rows": [
            { "bucket": "0.00-0.05", "count": 34, "tp": 0,  "fp": 34 },
            { "bucket": "0.25-0.30", "count": 12, "tp": 8,  "fp": 4  },
            { "bucket": "0.30-0.35", "count": 45, "tp": 45, "fp": 0  },
            ...
        ],
        "threshold": 0.29352656
    }
    """
    try:
        rows = query(
            get_conn,
            """
            SELECT
                FLOOR(score / 0.05) * 0.05            AS bucket_start,
                COUNT(*)                               AS count,
                SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp,
                SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp
            FROM predicted.eventos
            WHERE score IS NOT NULL
            GROUP BY bucket_start
            ORDER BY bucket_start ASC
            """
        )

        # Format bucket label as "0.25-0.30"
        formatted = []
        for r in rows:
            start = float(r["bucket_start"])
            end   = round(start + 0.05, 2)
            formatted.append({
                "bucket": f"{start:.2f}-{end:.2f}",
                "count":  int(r["count"]),
                "tp":     int(r["tp"]),
                "fp":     int(r["fp"]),
            })

        return jsonify({"rows": formatted, "threshold": 0.29352656})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/charts/severity", methods=["GET"])
def api_charts_severity():
    """
    Returns TP/FP count grouped by severity level.

    Response shape:
    {
        "rows": [
            { "severity": "high",   "tp": 30, "fp": 5  },
            { "severity": "medium", "tp": 12, "fp": 20 },
            ...
        ]
    }
    """
    try:
        rows = query(
            get_conn,
            """
            SELECT
                COALESCE(severity, 'unknown') AS severity,
                SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp,
                SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp
            FROM predicted.eventos
            GROUP BY severity
            ORDER BY tp + fp DESC
            """
        )

        return jsonify({"rows": [dict(r) for r in rows]})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/charts/top_rules", methods=["GET"])
def api_charts_top_rules():
    """
    Returns the most frequent alert rules and their TP/FP breakdown.

    Query params:
      ?limit=N   (default: 10)

    Response shape:
    {
        "rows": [
            { "rule": "Brute Force Detected", "tp": 40, "fp": 5,  "total": 45 },
            ...
        ]
    }
    """
    try:
        limit = min(int(request.args.get("limit", 10)), 50)

        rows = query(
            get_conn,
            """
            SELECT
                COALESCE(orig_rule_title, 'unknown') AS rule,
                SUM(CASE WHEN prediction = true  THEN 1 ELSE 0 END) AS tp,
                SUM(CASE WHEN prediction = false THEN 1 ELSE 0 END) AS fp,
                COUNT(*) AS total
            FROM predicted.eventos
            GROUP BY orig_rule_title
            ORDER BY total DESC
            LIMIT %s
            """,
            (limit,)
        )

        return jsonify({"rows": [dict(r) for r in rows]})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: LOGS — tail of log files
# ============================================================

@app.route("/api/logs", methods=["GET"])
def api_logs():
    """
    Returns the last N lines of the log files.

    Query params:
      ?source=splunk|predict|all   (default: all)
      ?lines=N                     (default: 100)

    Response shape:
    {
        "logs": [
            {
                "source":    "predict",
                "filename":  "auto_predict.log",
                "lines": ["2025-05-01 12:00:00 | OK event_id=...", ...]
            },
            ...
        ]
    }
    """
    try:
        source = request.args.get("source", "all")
        n_lines = min(int(request.args.get("lines", 100)), 500)

        def read_tail(filepath, n):
            try:
                with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                    return f.readlines()[-n:]
            except FileNotFoundError:
                return []

        def get_latest_log(prefix):
            """Return the active log file (logs/<prefix>.log) or most recent dated one."""
            active = os.path.join(LOG_DIR, f"{prefix}.log")
            if os.path.exists(active):
                return active
            # Fallback: most recently modified dated file
            pattern = os.path.join(LOG_DIR, f"{prefix}_*.log")
            files = glob.glob(pattern)
            return max(files, key=os.path.getmtime) if files else None

        result = []

        sources_map = {
            "splunk":  "auto_splunk",
            "predict": "auto_predict",
        }

        targets = sources_map if source == "all" else {source: sources_map[source]} if source in sources_map else {}

        for src_key, prefix in targets.items():
            filepath = get_latest_log(prefix)
            lines = read_tail(filepath, n_lines) if filepath else []
            result.append({
                "source":   src_key,
                "filename": os.path.basename(filepath) if filepath else f"{prefix}.log (not found)",
                "lines":    [l.rstrip("\n") for l in lines],
            })

        return jsonify({"logs": result})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# API: CLIENTS — list of unique clients (for filter dropdowns)
# ============================================================

@app.route("/api/clients", methods=["GET"])
def api_clients():
    """
    Returns the list of unique orig_client values in alertas_predicted.
    Used to populate filter dropdowns in the UI.

    Response shape:
    {
        "clients": ["client_a", "client_b", ...]
    }
    """
    try:
        rows = query(
            get_conn,
            "SELECT DISTINCT orig_client FROM predicted.eventos WHERE orig_client IS NOT NULL ORDER BY orig_client"
        )
        return jsonify({"clients": [r["orig_client"] for r in rows]})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ============================================================
# MAIN
# ============================================================
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)